# Generated by Django 6.0 on 2025-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(max_length=200)),
                ('Platos', models.CharField(max_length=200)),
                ('Imagenes', models.CharField(max_length=20)),
                ('Precio', models.CharField(max_length=200)),
                ('Alergia', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
