# Generated by Django 6.0 on 2025-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_suma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suma',
            name='Alergia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='suma',
            name='Imagenes',
            field=models.CharField(max_length=500),
        ),
    ]
