# Generated by Django 6.0 on 2025-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0003_alter_suma_alergia_alter_suma_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suma',
            name='Alergia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
