# Generated by Django 6.0 on 2025-12-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0004_alter_suma_alergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AImagenAler', models.CharField(max_length=500)),
                ('Informacion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEspecifico', models.CharField(max_length=200)),
            ],
        ),
    ]
