# Generated by Django 6.0 on 2025-12-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0005_alergias_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alergias',
            old_name='AImagenAler',
            new_name='ImagenAler',
        ),
    ]
