# Generated by Django 6.0 on 2025-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0006_rename_aimagenaler_alergias_imagenaler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suma',
            name='Alergia',
        ),
        migrations.AddField(
            model_name='suma',
            name='alergias',
            field=models.ManyToManyField(blank=True, related_name='platos', to='proyects.alergias'),
        ),
    ]
